apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy473
  labels:
    app: autodeploy473
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1717527571395
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy473
  template:
    metadata:
      labels:
        app: autodeploy473
    spec:
      containers:
        - name: autodeploy473
          image: acrworkflow1717527571395.azurecr.io/image-workflow-1717527571395:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
