apiVersion: v1
kind: Service
metadata:
  name: autodeploy473
  namespace: namespace-workflow-1717527571395
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy473
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000